### ISSUE TITLE
Add convars and stuff on the wiki.

### ISSUE THREAD

**Issue by Vurv78** [Vurv78/VExtensions#11]
Generate docs that'll be hosted on github.io (or the wiki, not sure rn) with the list of convars and functions

**Comment by Cheatoid** [comment]
I started an experimental branch to explore GitHub Markdown stuff...
https://github.com/Cheatoid/VExtensions/tree/readme-update

**Comment by Vurv78** [comment]
Looks really cool and yeah that's a nice idea. I wanna look into making a doc generator for this stuff
Since we already have separate modules and stuff, we can just look into what file created what e2 function

Everything else should be relatively easy to do

**Comment by Cheatoid** [comment]
I have made a few more updates, [check it out](https://github.com/Cheatoid/VExtensions/tree/readme-update#readme).
