### ISSUE TITLE
Here we go: The First Patch

### ISSUE THREAD

**Issue by Cheatoid** [Vurv78/VExtensions#14]
👋 (it is me, you know me as [`0` from 🇬](https://steamcommunity.com/profiles/76561198119930042/))

I come here to tell you I'd like to contribute to your work, so I hope you're cool with that.
I have small experience with git, so let's get to it.

There are still several bugs around and I fixed some stuff last night.
Anyways, I will create the pull request in a moment, so we can continue from there 🚀

(P.S. Perhaps rename your GitHub account to *Vurvoid*, while it is still not taken! 😆)

**Comment by Vurv78** [comment]
Yeah of course! You can make any PRs or issues at any time, it doesn't really matter. There's a lot of things that could be improved and added in this addon and the more help the better, lemme know if you need something on the discord

**Comment by Cheatoid** [comment]
@Vurv78 I have created the PR: #15
It is still WIP, but go on, take a look and tell me what do you think about the changes so far?

**Comment by Vurv78** [comment]
They all look really good, I should have cleaned up all of this code myself but tysm 👍 , I was wondering about using four spaces instead of tabs, that kind of looks terrible in my vscode setup, is there some kind of technical reason to use spaces instead of tabs

And im working on overhauling some of the functions like luatbltoe2 and getE2Type by looking more into the compiler and how it checks for types. 

I don't think the compiler actually knows for sure what type it is, just looks for if it fits the criteria, which is a huge problem here in case of people making unnecessary types like in wire extras with the "tracedata" type, that is literally just a lua table of data, giving a huge headache to us. Would be nice if all e2 objects had some better identifiers.

Will start replying to the reviews now

**Comment by Vurv78** [comment]
https://github.com/wiremod/wire-extras/blob/master/lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua#L1333 Pain

**Comment by Cheatoid** [comment]
> They all look really good, I should have cleaned up all of this code myself but tysm 👍

Fantastic 😄

> I was wondering about using four spaces instead of tabs, that kind of looks terrible in my vscode setup, is there some kind of technical reason to use spaces instead of tabs

Yes, use spaces, is always nicer because you get better flexibility for code alignment. Tabs are pain.
Also fun fact: E2 editor doesn't like tabs.
I don't have any issues on my side with VSC, because I have configured it to always use spaces:
![image](https://user-images.githubusercontent.com/13347909/100822113-fc9bdb00-3451-11eb-9ceb-511503785233.png)
So when I press Tab, it will insert 4 spaces (see the little dots in the selected code behind the popup, they indicate a whitespace is used instead of tab). Likewise when I press backspace at that point, it will remove those 4 spaces at once. So it works just like you're using tabs (but you are not).
The behavior is the same with Sublime Text too. Not sure what could be the problem on your side.

> And im working on overhauling some of the functions like luatbltoe2 and getE2Type by looking more into the compiler and how it checks for types. [...]

I know right, I feel the pain...

----

I got one general question tho, I had noticed and forgot to ask in the beginning.
Why do you have 2 repositories for the Coroutine core? 😕
(Please dont tell me I will have to move stuff around and have duplicate code, the helper functions again)

**Comment by Vurv78** [comment]
I have two repos for CoroutineCore so I can ship that other repo to the workshop. This is the main branch tho, I'll just copy and paste the code over. I might even just get rid of the workshop version, working with the workshop is tedious..

These reviews are taking ages, you know of anything that's actually dedicated to doing these? I'm using vscode extensions right now.

**Comment by Cheatoid** [comment]
> I have two repos for CoroutineCore so I can ship that other repo to the workshop. This is the main branch tho, I'll just copy and paste the code over. I might even just get rid of the workshop version, working with the workshop is tedious..

Oh ok. You could automate things out using GitHub Actions, it is amazing. You could set it up to push a new workshop update when you create a tagged commit, or only when you push to specific branch, etc. etc.
I haven't done this myself, but I know it can be done. If that's what you would like to do, we can research that area.

> These reviews are taking ages, you know of anything that's actually dedicated to doing these? I'm using vscode extensions right now.

Probably, not sure, I'd just use GitHub web UI (in webbrowser). Go to the [PR `Files changed` page](https://github.com/Vurv78/VExtensions/pull/15/files), there you can tick "Viewed" to hide the file and use "Resolved conversation" to hide comments, which I think is helpful.

![image](https://user-images.githubusercontent.com/13347909/100823574-bdbb5480-3454-11eb-902a-f5ea5d3c9301.png)

**Comment by Vurv78** [comment]
Rewrote the e2table functions, should be all good. I tested on gmod and it seemed to work fine
