### ISSUE TITLE
The Second Patch

### ISSUE THREAD

**Issue by Cheatoid** [Vurv78/VExtensions#17]
Here we go, round 2.

- [x] Fix `try` function (type inference issues)
- [x] Implement table-based ~~vararg~~ support for `try` & `coroutine:resume`/`yield`
- [x] Write docs for the new functions (mostly selfaware2)
- [x] Set E2 function costs (make some benchmark kind of testing and find a good balance)
- [ ] Fix any remaining bugs?

**Comment by Vurv78** [comment]
Already working on this as a status update, Just trying to work on try's varargs to make it work correctly. Right now trying to make it properly error the main thread (or the 'try' thread) (probably main) if you give args that the function doesn't ask for or give no args

There's probably an e2lib function for this somewhere..

**Comment by Cheatoid** [comment]
I can do the overload solution PR, as I mentioned in another issue, this can't be done perfectly because vararg support would rely on the `luaTableToE2`, besides that, E2 function can't return vararg as mentioned as well, so I think the best thing to pass around would be a `table`.
Example with `try`, I'd introduce a new e2function:
`e2function table try(table data)`
And of course, you'd just to need adjust the UDF signature (when using this overload), like in the following example:
```golo
function table myFunc( Data:table ) # Return type: table. First argument type: table.
{
    print( "myFunc data table:" )
    printTable( Data )
    return table( "Result coming back...", owner() )
}

printTable( try( "myFunc", table( "Args here...", 123 ) ) )
```

This would definitely do the job (for the time being). I don't want to mess around with `luaTableToE2` at all, cuz that's just a bigass hack.

It is not perfect, and the sad part is: it can't even be made perfect 😭
(This will only always work perfectly for Starfall, because there it just uses GLua.)

**Comment by Vurv78** [comment]
Yeah, I think we're gonna have to transport a table rather than varargs.. Otherwise we'd deal with type inference all over again and that would just be... terrible..

I think from now on, we should have a policy to only use type inference in functions that simply return data structures that aren't meant to really be used, like with the getBuiltinFuncInfo and other functions.

**Comment by Cheatoid** [comment]
The cool thing about passing a table to the UDF, is that you can alter the `data` (argument) table and then read it back even if UDF throws an error, because it is pass-by-reference:
```golo
function table myFunc( Data:table )
{
    Data[ 1, string ] = "We have come this far"
    error( "get out" )
    # It is fine by E2 to omit the return statement  ;)
}
local Args = table()
try( Args )
printTable( Args )
```

> 1	=	We have come this far

**Comment by Cheatoid** [comment]
I have specialized the "luaTableToE2" for the `try` function(s).
They are now returning a value which is perfectly type-safed 😄
