### ISSUE TITLE
Enable GitHub Discussions feature

### ISSUE THREAD

**Issue by Cheatoid** [Vurv78/VExtensions#21]
A brand new *beta* feature is available on GitHub: Discussions 💯
1. Go to [Settings](https://github.com/Vurv78/VExtensions/settings).
2. Enable `Discussions` under *Features*.
3. Click `Setup` and then just proceed.

Bonus: As well as the Dark theme (which can be enabled in [personal settings](https://github.com/settings/profile)). 🚀

**Comment by Vurv78** [comment]
Done, thanks
