### ISSUE TITLE
PrintGlobal Issues / Suggestions List

### ISSUE THREAD

**Issue by Vurv78** [Vurv78/VExtensions#5]
Here's a list of PrintGlobal's issues that are needed to be fixed, I will attempt to fix these for the time and once all of the issues of this addon are complete a new release will be made. Feel free to try and take these on.

> * [x] Add support for non-strings
> * [x] Add support for sending to a single player if a player is provided as the first argument

**Comment by Fasteroid** [comment]
passing a non player as the first argument kills it

**Comment by Vurv78** [comment]
@Fasteroid both of these are now done 👍
